### PR TITLE
Add Scala 3.0.0-RC1

### PR DESCRIPTION
**Pull request by lrlucena**

### CODE REVIEW

**Comment by marc0der** [comment]
@lrlucena formatting issue so build is broken, sorry.

**Comment by anaumidis** [comment]
@lrlucena any progress on this?

**Comment by marc0der** [comment]
@anaumidis feel free to submit a new PR based on this if you like. It just needs a run of `scalafmt` on the code.

**Comment by lrlucena** [comment]
Scala 3.0.0-RC1 is already included

**Pull request closed without merging**
