### PR TITLE
Bump same JDKs

### PR DESCRIPTION
**Pull request by poad**
Bump each JDKs
 - SapMachine to 11.0.6
 - Zulu 13 to 13.0.2
 - Zulu 11 to 11.0.6
 - Zulu 8 to 8u242
 - Amazon Corretto 11 to 11.0.6
 - Amazon Corretto 8 to 8u242
 - Liberica 13 to 13.0.2
 - Liberica 11 to 11.0.6
 - Liberica 8 to 8u242
 - java.net OpenJDK 13 to 13.0.2
 - AdoptOpenJDK 11(hotspot) to 11.0.6
 - AdoptOpenJDK 11(OpenJ9) to 11.0.6

### CODE REVIEW

**Comment by marc0der** [comment]
@poad thanks for raising this PR. I'll need a few changes before merging though.

Firstly, database migrations are always immutable and can only be run once. We need brand new changelogs for each entry you want to add.

Secondly, the file you edited is marked deprecated and has been superceded by vendor specific classes for the individual Java vendors, found in the java package. If you add new entries, please add them to the appropriate changeset.

Once that is done I'd be happy to merge.

**Comment by poad** [comment]
@marc0der Thank you for your reply.
Though I think that it takes time a little, I change it each.

Is the Java Vender file "src/main/scala/io/sdkman/changelogs/java/*Migrations.scala?"

**Comment by marc0der** [comment]
That's right yes. It should be pretty easy to do. Feel free to jump onto slack if you want to ask me anything.

**Comment by poad** [comment]
@marc0der 
I do fail without being able to download a binary in the present master branch, get out of my face.
May I delete the bank commenting out in fad88823852f4858375f6a6c85c3c09abe7e473e?

I added changeSet to remove each entry from DB just to make sure.
However, I commented out and just moved it first as changeSet of a certain openjdk-14-ea+18 and openjdk-14-ea+20 worked, and migrate did fail.
May I delete changeSet of a certain openjdk-14-ea+18 and openjdk-14-ea+20 now?

```
[main] ERROR io.sdkman.changelogs.package$$anon$1 - URL https://download.java.net/java/early_access/jdk14/18/GPL/openjdk-14-ea+18_linux-x64_bin.tar.gz responded with text/html content-type detected
[main] INFO com.github.mongobee.Mongobee - Mongobee is releasing process lock.
Exception in thread "main" com.github.mongobee.exception.MongobeeException: Invalid url: https://download.java.net/java/early_access/jdk14/18/GPL/openjdk-14-ea+18_linux-x64_bin.tar.gz
        at com.github.mongobee.Mongobee.executeMigration(Mongobee.java:200)
        at com.github.mongobee.Mongobee.execute(Mongobee.java:156)
        at io.sdkman.DbMigration$.delayedEndpoint$io$sdkman$DbMigration$1(DbMigration.scala:10)
        at io.sdkman.DbMigration$delayedInit$body.apply(DbMigration.scala:5)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at io.sdkman.DbMigration$.main(DbMigration.scala:5)
        at io.sdkman.DbMigration.main(DbMigration.scala)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.github.mongobee.Mongobee.executeChangeSetMethod(Mongobee.java:235)
        at com.github.mongobee.Mongobee.executeMigration(Mongobee.java:181)
        ... 12 more
Caused by: com.github.mongobee.exception.MongobeeChangeSetException: Invalid url: https://download.java.net/java/early_access/jdk14/18/GPL/openjdk-14-ea+18_linux-x64_bin.tar.gz
        at io.sdkman.changelogs.package$$anon$1.validUrl(package.scala:35)
        at io.sdkman.changelogs.package$$anon$1.validUrl(package.scala:27)
        at io.sdkman.changelogs.package$$anon$4.$anonfun$validUrl$1(package.scala:42)
        at io.sdkman.changelogs.package$$anon$4.$anonfun$validUrl$1$adapted(package.scala:42)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at io.sdkman.changelogs.package$$anon$4.validUrl(package.scala:42)
        at io.sdkman.changelogs.package$$anon$4.validUrl(package.scala:39)
        at io.sdkman.changelogs.package$ValidationOps.validate(package.scala:74)
        at io.sdkman.changelogs.JavaMigrations.migrate196(JavaMigrations.scala:378)
        ... 18 more

> Task :run FAILED

FAILURE: Build failed with an exception.
```


```
[main] ERROR io.sdkman.changelogs.package$$anon$1 - URL https://download.java.net/java/early_access/jdk14/20/GPL/openjdk-14-ea+20_linux-x64_bin.tar.gz responded with text/html content-type detected
[main] INFO com.github.mongobee.Mongobee - Mongobee is releasing process lock.
Exception in thread "main" com.github.mongobee.exception.MongobeeException: Invalid url: https://download.java.net/java/early_access/jdk14/20/GPL/openjdk-14-ea+20_linux-x64_bin.tar.gz
        at com.github.mongobee.Mongobee.executeMigration(Mongobee.java:200)
        at com.github.mongobee.Mongobee.execute(Mongobee.java:156)
        at io.sdkman.DbMigration$.delayedEndpoint$io$sdkman$DbMigration$1(DbMigration.scala:10)
        at io.sdkman.DbMigration$delayedInit$body.apply(DbMigration.scala:5)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at io.sdkman.DbMigration$.main(DbMigration.scala:5)
        at io.sdkman.DbMigration.main(DbMigration.scala)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.github.mongobee.Mongobee.executeChangeSetMethod(Mongobee.java:235)
        at com.github.mongobee.Mongobee.executeMigration(Mongobee.java:181)
        ... 12 more
Caused by: com.github.mongobee.exception.MongobeeChangeSetException: Invalid url: https://download.java.net/java/early_access/jdk14/20/GPL/openjdk-14-ea+20_linux-x64_bin.tar.gz
        at io.sdkman.changelogs.package$$anon$1.validUrl(package.scala:35)
        at io.sdkman.changelogs.package$$anon$1.validUrl(package.scala:27)
        at io.sdkman.changelogs.package$$anon$4.$anonfun$validUrl$1(package.scala:42)
        at io.sdkman.changelogs.package$$anon$4.$anonfun$validUrl$1$adapted(package.scala:42)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at io.sdkman.changelogs.package$$anon$4.validUrl(package.scala:42)
        at io.sdkman.changelogs.package$$anon$4.validUrl(package.scala:39)
        at io.sdkman.changelogs.package$ValidationOps.validate(package.scala:74)
        at io.sdkman.changelogs.java.OpenJdkMigrations.migrate001(OpenJdkMigrations.scala:16)
        ... 18 more

> Task :run FAILED
```

**Comment by marc0der** [comment]
I'd suggest closing this PR and just starting over. It will be simpler to take the learnings gathered out of this one and simply raising a new PR with a single commit. Wdyt?

**Comment by poad** [comment]
@marc0der 
Thank you for reviewing it.

It is easy to confirm the one that I surely distributed finely.
This request does close and decides to distribute it according to vendors, and to request it.

**Pull request closed without merging**
