### PR TITLE
Added ZuluFX 11.0.6

### PR DESCRIPTION
**Pull request by poad**

### CODE REVIEW

**Comment by marc0der** [comment]
Would you mind cleaning up the commits of this PR please?
Perhaps you can have only 2 commits:
* clean up openjdk migrations
* add the new fx-zulu java versions and delete old.

Feel free to force-push to your feature branch.

**Comment by poad** [comment]
@marc0der Thx for review!
OK! Will cleanup the commits.

**Comment by poad** [comment]
@marc0der 
I cleaned commits.
Please re-review again.

**Comment by marc0der** [comment]
Looks great, thank you!

**Comment by poad** [comment]
Thx!

**Pull request merged**
