### PR TITLE
Add Scala 2.13.4

### PR DESCRIPTION
**Pull request by BalmungSan**

### CODE REVIEW

**Comment by BalmungSan** [comment]
Uhm, the error in CI seems to be unrelated to my change, any thoughts about it?

**Review by helpermethod — APPROVED** [review]
Looks good to me! Thanks for submitting!

**Comment by helpermethod** [comment]
> Uhm, the error in CI seems to be unrelated to my change, any thoughts about it?

Yes, the CI error has nothing to do with you change.

**Comment by eddumelendez** [comment]
Depends on https://github.com/sdkman/sdkman-db-migrations/pull/432

**Pull request merged**
