### PR TITLE
Update Tomcat versions to the latest

### PR DESCRIPTION
**Pull request by chubbard**
Updated the versions of Apache Tomcat to the latest versions for series 7 -> 7.0.109, 8.5 -> 8.5.73, 9 -> 9.0.55, and 10 -> 10.0.13.  Also updated the default candidate from 9 to 10 since 10 has been officially released now.

### CODE REVIEW

**Review by eddumelendez — CHANGES_REQUESTED** [review]
new migration should be added. updating existing one will not apply the change.

**Comment by ahmadshalabi** [comment]
> new migration should be added. updating existing one will not apply the change.

@eddumelendez, I did the necessary change in this [pull request](https://github.com/sdkman/sdkman-db-migrations/pull/573)

**Comment by marc0der** [comment]
@ahmadshalabi database migrations are always immutable. you need to add a new migration below the existing one (with a new changelog number) for it to take effect.

**Comment by eddumelendez** [comment]
closing because those and even greater versions are already available via sdkman

**Pull request closed without merging**
