### PR TITLE
Add bpipe 0.9.9.5 to SDKMan

### PR DESCRIPTION
**Pull request by ssadedin**
This PR is to add Bpipe, a tool that I am the author of (see http://bpipe.org) to SDKMan.

Thanks!

### CODE REVIEW

**Comment by ssadedin** [comment]
Ok - I've taken the version out. Not sure if it is a problem that the Candidate still refers to a default version, even though it doesn't exist?

Thanks!

**Comment by marc0der** [comment]
Yes that will break, simply turn the default version to None or remove it
all together (it will automatically be set to None)

**Comment by ssadedin** [comment]
Ok - removed the version for now.

Let me know any other issues!

**Comment by marc0der** [comment]
Thanks!

**Pull request merged**
