### PR TITLE
Add dotty

### PR DESCRIPTION
**Pull request by Miuler**

### CODE REVIEW

**Comment by marc0der** [comment]
@Miuler Thanks for raising this PR. It will be super exciting to have Dotty on SDKMAN! Looks like your fork needs to be rebased though. We will also need to [add the Candidate](https://github.com/sdkman/sdkman-db-migrations#adding-a-new-candidate) as we don't have one for Dotty yet.

**Comment by Miuler** [comment]
@marc0der ok, I will check it. Thanks

**Comment by abhsrivastava** [comment]
Hi Any progress on this? I was hoping to manage dotty installation from sdkman

**Comment by marc0der** [comment]
Dotty has been added, so closing this PR.

**Pull request closed without merging**
