### PR TITLE
Fixes #126, switched links for Linux and macOS

### LINKED ISSUE #126: Unable to install GraalVM CE 19.1.0 on macOS
Unable to install GraalVM CE 19.1.0 on macOS (Mojave 10.14.5)
Works well on Linux machine ...

```
sdk install java 19.1.0-grl
tr: Illegal byte sequence

Downloading: java 19.1.0-grl

In progress...

######################################################################## 100.0%

Repackaging Java 19.1.0-grl...
-bash: cd: /Users/rsvoboda/.sdkman/tmp/out/*/Contents: No such file or directory
mv: rename Home to /Users/rsvoboda/.sdkman/tmp/Java-19.1.0-grl: No such file or directory

zip error: Nothing to do! (try: zip -qyr /Users/rsvoboda/.sdkman/tmp/.zip . -i Java-19.1.0-grl)

Done repackaging...
Cleaning up residual files...
mv: rename /Users/rsvoboda/.sdkman/tmp/.zip to /Users/rsvoboda/.sdkman/archives/java-19.1.0-grl.zip: No such file or directory
unzip:  cannot find or open /Users/rsvoboda/.sdkman/archives/java-19.1.0-grl.zip, /Users/rsvoboda/.sdkman/archives/java-19.1.0-grl.zip.zip or /Users/rsvoboda/.sdkman/archives/java-19.1.0-grl.zip.ZIP.
rm: /Users/rsvoboda/.sdkman/archives/java-19.1.0-grl.zip: No such file or directory

Stop! The archive was corrupt and has been removed! Please try installing again.
```

### PR DESCRIPTION
**Pull request by rsvoboda**
Fixes #126, switched links for Linux and macOS

### CODE REVIEW

**Comment by marc0der** [comment]
Sorry, looks like the db migration has caused havoc. It also Java list view. I'll investigate shortly.

**Comment by marc0der** [comment]
Also please use slack as per the contributor guidelines. Closing this issue as it is a data problem not a bug.

**Comment by marc0der** [comment]
This will require a brand new migration as every migration can only be run once.

**Comment by rsvoboda** [comment]
What should be the new version - 19.1.0-grl is taken now

**Comment by marc0der** [comment]
Closing this as it has been resolved.

**Comment by rsvoboda** [comment]
Thanks for quick fix

**Pull request closed without merging**
