### PR TITLE
Add Java 8.0.211

### PR DESCRIPTION
**Pull request by eddumelendez**

### CODE REVIEW

**Comment by marc0der** [comment]
Not sure if you saw my [announcement on Twitter](https://twitter.com/marc0der/status/1118260924060721155), but due to the new licensing on SDKMAN we are no longer going to be supporting Oracle JDKs.

**Comment by eddumelendez** [comment]
I missed that tweet. I will close this PR.

**Comment by eddumelendez** [comment]
regarding to this. I guess openjdk will ok, right? https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=hotspot

**Comment by marc0der** [comment]
For sure, although it will fall under the category of AdoptOpenJDK, not OpenJDK. We would want both hotspot and j9 variants as we have it atm.

**Pull request closed without merging**
