### PR TITLE
add adoptopenjdk 8 202

### PR DESCRIPTION
**Pull request by mattluce**

### CODE REVIEW

**Comment by andrebrait** [comment]
What is the point, if `8.0.282.open-adpt` is already there?

**Comment by mattluce** [comment]
Our team needs a very specific version of the jdk. However, there may be better ways than adding it to the global repository.

**Comment by marc0der** [comment]
Apart from that, the URL is invalid and failing to build.

**Comment by mattluce** [comment]
I think that failing URL is for a different library. It looks like other PRs may have had the same issue.

Anyway, I'll work on a different way of managing the specific version.

**Pull request closed without merging**
