### PR TITLE
Add Maven 3.9.5

### PR DESCRIPTION
**Pull request by aalmiray**

### CODE REVIEW

**Review by helpermethod — APPROVED** [review]
LGTM!

**Review by cstamas — APPROVED** [review]

**Comment by eshackelford-ias** [comment]
Can this be merged please?

**Comment by helpermethod** [comment]
> Can this be merged please?

I hope @aalmiray doesn't mind that I've pushed the button 😅

**Comment by aalmiray** [comment]
@helpermethod you did wut mate? Of course I don’t mind 🎉🚀

**Pull request merged**
