### PR TITLE
Add GraalVM 1.0.0-RC16 CE

### PR DESCRIPTION
**Pull request by wololock**
Release notes: https://github.com/oracle/graal/releases/tag/vm-1.0.0-rc16

### CODE REVIEW

**Comment by ilopmar** [comment]
@wololock can you please also delete Graal versions rc8 to rc12 both inclusive? Thanks!

**Comment by wololock** [comment]
@ilopmar Yes, it makes sense to clean-up old RC versions a bit. Updating the pull request then.

**Comment by marc0der** [comment]
Thank you!

**Comment by ilopmar** [comment]
:tada:

**Comment by marc0der** [comment]
Thanks!

**Pull request merged**
