### PR TITLE
Add Java GA 11.0.3

### PR DESCRIPTION
**Pull request by eddumelendez**

### CODE REVIEW

**Comment by marc0der** [comment]
Thanks!

**Comment by marc0der** [comment]
I've had to pull this from SDKMAN. AdoptOpenJDK is not the same as OpenJDK.

AdoptOpenJDK Java versions have a suffix `-adpt`, while all Java originating from [java.net](http://jdk.java.net/11/) have a suffix of `-open`. As it currently stands, they are no longer releasing new versions of openjdk 11.

Sorry, my slip up. I should have noticed.

**Comment by Powerrr** [comment]
@marc0der Could you also re-add `11.0.2-open` candidate? (seems like this migration deleted it)

**Comment by marc0der** [comment]
@eddumelendez any chance that you could bring the erroneously deleted `11.0.2-open` java version back please?

**Comment by eddumelendez** [comment]
@marc0der sure! I will.

**Comment by marc0der** [comment]
Thanks for helping out @eddumelendez. Really appreciate your help!

**Comment by eddumelendez** [comment]
glad to help! :)

**Pull request merged**
