### PR TITLE
Add GraalVM 20.3.0

### PR DESCRIPTION
**Pull request by eddumelendez**

### CODE REVIEW

**Review by marc0der — APPROVED** [review]

**Comment by ilopmar** [comment]
@marc0der can you please merge this? :pray:

**Comment by ilopmar** [comment]
Thank you @eddumelendez :100:

**Comment by eddumelendez** [comment]
looks like urls changed. I have opened #428

**Comment by ilopmar** [comment]
Ohh, I see. I was about to ask because I don't see the new versions ready to install from the CLI. I'll wait until the other PR is merged.

**Pull request merged**
