### PR TITLE
Add GraalVM 20.2.0

### PR DESCRIPTION
**Pull request by eddumelendez**

### CODE REVIEW

**Review by ilopmar — APPROVED** [review]

**Comment by ilopmar** [comment]
@eddumelendez you are always the first one to submit these PRs! :-)

**Comment by ilopmar** [comment]
@marc0der can you please merge this? :pray:

**Comment by marc0der** [comment]
Sorry for the holdup!

**Comment by ilopmar** [comment]
Don't worry! :)

**Pull request merged**
