### PR TITLE
sbt migration to GitHub Releases

### PR DESCRIPTION
**Pull request by eed3si9n**

### CODE REVIEW

**Comment by eddumelendez** [comment]
@eed3si9n can you provide more context about it. `sbt` is already provided by `sdkman` but not sure if something changed.

**Comment by marc0der** [comment]
Thank you!

**Comment by marc0der** [comment]
@eed3si9n looks like it's broken the build.

**Comment by eed3si9n** [comment]
Trying again - https://github.com/sdkman/sdkman-db-migrations/pull/349

**Pull request merged**
