### PR TITLE
 Add new AdoptOpenJDK updates for 8 and 11 for OpenJ9 and Hotspot variants

### PR DESCRIPTION
**Pull request by kjjaeger**
Add 4 updated JDKs for AdoptOpenJDK version 8 and 11 in OpenJ9 and HotSpot variants.
8.0.212.j9-adpt, 11.0.3.j9-adpt, 8.0.212.hs-adpt, and 11.0.3.hs-adpt

### CODE REVIEW

**Comment by marc0der** [comment]
This PR will need a rebase and some changes to the changelog sequence.

**Comment by kjjaeger** [comment]
Do I need to renumber starting with a order values starting at 125?  It looks like there is a gap from 118 to 121.  A little confused here.

**Comment by kjjaeger** [comment]
Also, I am still seeing the changeset with order 117, which I thought was now invalid and should be removed.

**Comment by marc0der** [comment]
Sorry to mess you around but I think @eddumelendez in #102 already added these AdoptOpenJDK builds. Maybe take a look at that PR for future reference wrt how it should be done. Anyway, thanks a lot for putting in all the effort!

**Comment by kjjaeger** [comment]
Yes it looks like he did.  Thanks anyway.  Just glad to see them added.

**Pull request closed without merging**
