### PR TITLE
Add dependency-watch candidate

### PR DESCRIPTION
**Pull request by eygraber**

### CODE REVIEW

**Review by helpermethod — APPROVED** [review]
LGTM!

**Comment by marc0der** [comment]
I think the take-away here was that @eygraber isn't affiliated with the project, so unfortunately we can't add this.

**Comment by marc0der** [comment]
Would you mind reverting this somehow @helpermethod?

**Comment by marc0der** [comment]
It will need to be cleared from the database too. I can handle that.

**Pull request merged**
