### PR TITLE
Add AdoptOpenJDK Hotspot 222

### PR DESCRIPTION
**Pull request by henri-tremblay**

### CODE REVIEW

**Review by marc0der — CHANGES_REQUESTED** [review]
Hi @henri-tremblay, 

Thanks for this PR!

It seems like the build is broken due to an orphaned binary. I'll be happy to merge if the build is green.

Also, we need to set this version as explicitly hidden.

**Comment by henri-tremblay** [comment]
The build is indeed broken. But that doesn't seem caused by me. It's about a missing Loom binary.

**Comment by henri-tremblay** [comment]
I don't know how you fix that normally. There are 3 early access versions that are not available anymore, I tried to remove them in a new change set but it doesn't work because it fails on the old charsets. Shall I delete the 3 problematic change sets? Build passes if I do so.

**Comment by henri-tremblay** [comment]
I look at other PRs and it seems to be the way to go. So I've deleted the 3 obsolete change sets

**Comment by henri-tremblay** [comment]
Weird. The failure is now a false negative. I don't see how I could re-run the checks.

**Comment by marc0der** [comment]
I usually run the migration locally as suggested in the README and remove any defunct migrations in a second commit.

**Comment by marc0der** [comment]
Never mind, I see that is exactly what you did 😀

**Review by marc0der — APPROVED** [review]
LGTM.

**Pull request merged**
