### PR TITLE
Added Zulu 8u265 and ZuluFX 8u265

### PR DESCRIPTION
**Pull request by poad**
## Added
 - Zulu 8u265(https://github.com/sdkman/sdkman-db-migrations/pull/309/commits/8660fa0b7496f67c8d24baca743213f9a9da3721)
 - Zulu FX 8u265(https://github.com/sdkman/sdkman-db-migrations/pull/309/commits/4d88e1a69d16a0cf7290502090ea6f3fe8f604e4)

## Remove
 - Zulu FX 8u262(https://github.com/sdkman/sdkman-db-migrations/pull/309/commits/d814d6d99900c8c385f26b71eeced0058519110a)

### CODE REVIEW

**Comment by marc0der** [comment]
It is very difficult to view this diff, what blocks have been added/removed?

**Comment by poad** [comment]
@marc0der 
Thank you!
Oops! I've included some extra changes.
I will organize it to include commits so that only the necessary ones remain.

**Comment by poad** [comment]
@marc0der 
We've organized the commitments appropriately.

The title hasn't changed, but we've added 8u265 and removed 8u262 from ZuluFX with it.

I've included the changes with the commit hash in the description.

**Comment by marc0der** [comment]
Thank you!

**Pull request merged**
