### PR TITLE
openjdk 15ea31 and 16ea5

### PR DESCRIPTION
**Pull request by eddumelendez**
- Add OpenJDK 15ea31
- Add OpenJDK 16ea5

### CODE REVIEW

**Comment by eddumelendez** [comment]
@marc0der broke the build at #287 😢 I have updated this PR with the fix

**Comment by marc0der** [comment]
I fixed it (and also made some optimisations). Please let me know how you like the change.
Shall we do subsequent migrations in this style going forward? wdyt?

**Comment by eddumelendez** [comment]
thanks for fixing it! and the change looks much better! I will update my PR

**Comment by eddumelendez** [comment]
@marc0der PR updated. hopefully no syntax error this time 🙈

**Comment by marc0der** [comment]
Looks great! I suggest we just keep reusing these three constructs from now on (in other words, increment the `ChangeSet`s and reuse these three blocks of code without accumulation). In the end, version control will give us all the history we require should we need it. How does it sound?

**Pull request merged**
