### PR TITLE
Upgrade Java

### PR DESCRIPTION
**Pull request by renannprado**

### CODE REVIEW

**Comment by renannprado** [comment]
Ah, I see.
It would be nice though if they provided the release candidate versions as well.

**Comment by renannprado** [comment]
@marc0der I've removed the gradle migrations

**Comment by marc0der** [comment]
Thanks for contributing!

**Comment by marc0der** [comment]
@renannprado You might want to ask them on their own forums why they haven't been releasing Gradle 5.x builds. Maybe something not set up in their build pipeline?

**Comment by renannprado** [comment]
@marc0der I'll certainly do that. Thanks for the hing!

**Pull request merged**
