### PR TITLE
add liquidbase candidate

### LINKED ISSUE #389: Feature: [Install liquibase cli from sdkman]
- [x] I have read the [CONTRIBUTING guidelines](CONTRIBUTING.md)

**Feature request**

It would be nice if it was possible to install [liquibase cli](https://www.liquibase.org/download) from **sdkman**.  
Liquibase is super useful tool to handle database versioning (migrations) in java programs.

Cheers

### PR DESCRIPTION
**Pull request by rfigueroa**
closes #389

### CODE REVIEW

**Comment by rfigueroa** [comment]
@eddumelendez @marc0der I don't think the build failing is related to this change, but I am not sure how to fix it either

**Comment by helpermethod** [comment]
Does the liquibase tar file contain a `bin` folder? Otherwise this won't work out of the box.

**Comment by rfigueroa** [comment]
> Does the liquibase tar file contain a `bin` folder? Otherwise this won't work out of the box.

it does not have a bin folder a `liquidbase` and `liquidbase.bat` script are at the root of the tar file

**Comment by marc0der** [comment]
In that case unfortunately it won't work. You could try raising this with the liquibase team.

**Pull request closed without merging**
