### PR TITLE
Adding candidate and Migration for Flink

### PR DESCRIPTION
**Pull request by ChethanUK**

### CODE REVIEW

**Comment by ChethanUK** [comment]
@marc0der Can you please review this PR

**Review by marc0der — COMMENTED** [review]
Thanks for this, Flink is a great candidate for SDKMAN!

One thing I'd suggest is to follow the same approach for adding versions as other candidates do. Consider looking at SBT as an example.

A top tip is that `List[Version]` also has an `insert` method.

It would also be great if we could get some more of the historic versions included, although that is only nice to have 😄

**Comment by ChethanUK** [comment]
@marc0der one quick question: Where is the source code of 1.4.* of sbt? 

I can only see till 1.3.* in https://github.com/sdkman/sdkman-db-migrations/blob/master/src/main/scala/io/sdkman/changelogs/SbtMigrations.scala#L23

```bash
sdk list sbt
zsh: correct 'sbt' to '.sbt' [nyae]? n
================================================================================
Available Sbt Versions
================================================================================
 > * 1.4.7               1.3.7               1.1.6
     1.4.6               1.3.6               1.1.5
     1.4.5               1.3.5               1.1.4
   * 1.4.4               1.3.4               1.1.2
     1.4.3               1.3.3               1.1.1
   * 1.4.2               1.3.1               1.1.0
     1.4.1               1.3.0               1.0.4
     1.4.0               1.2.8               1.0.3
     1.4.0-RC2           1.2.7               1.0.2
   * 1.3.13              1.2.6               1.0.1
     1.3.12              1.2.5               1.0.0
     1.3.11              1.2.4               0.13.18
   * 1.3.10              1.2.3               0.13.17
     1.3.9               1.2.1
   * 1.3.8               1.2.0
```

**Comment by marc0der** [comment]
Good question, the SBT versions are being published through our vendor API by @eed3si9n. The migration you see here was only a correction of some funky URLs.

**Comment by ChethanUK** [comment]
@marc0der Updated the PR

**Comment by ChethanUK** [comment]
Also, How to install SDK version from local setup? 

In Mac i followed following:
```bash
# MongoDB via Mac  Docker Desktop
docker run -d -p 27017:27017 --name=mongo mongo:3.2
# Ran migrations
./gradlew clean run
```

But even with SDK offline, not able to install with local setup. Are there any instructions on how to do this [Setup and install via local sdkman]?

**Comment by marc0der** [comment]
This is only for local development and testing. SDKMAN is backed by a slew of microservices that rely on our central database. These migrations give community members a chance to contribute to this database.

**Comment by ChethanUK** [comment]
Can you review and merge, please :)

Also, is a Pre or Post hook to install Java required?
I want to install 1.12.2 in local, current installations giving trouble when switching between 1.11 and 1.12 so want to install via sdkman. Thank You

**Comment by marc0der** [comment]
First off, thanks for your contribution!

I merged it manually but had to do a rebase against master. I think this confused GitHub so it isn't showing as merged but conflicting.

Hope you don't mind, but I also [simplified the code](https://github.com/sdkman/sdkman-db-migrations/commit/c8dbe2e0757ee5b5b3173a4766488e0678e19c67) somewhat to make it a bit more explicit.

Cheers!

**Comment by ChethanUK** [comment]
Where are the test cases?

sdk install is not working:
```bash
sdk install flink 1.12.2

Stop! flink is not a valid candidate.
```

**Pull request closed without merging**
