### PR TITLE
Fix formatting of maven-4-alpha-1 changeset

### PR DESCRIPTION
**Pull request by helpermethod**
This PR should fix the broken formatting of the MavenMigration.scala file (which somehow broke master).

### CODE REVIEW

**Comment by helpermethod** [comment]
@marc0der I have no idea why suddenly scalafmt complains. Locally everything works fine. I even created a fresh clone.

**Comment by marc0der** [comment]
@helpermethod You should be able to reformat the file by running `./gradlew scalafmt`. Let me know if that doesn't fix it.

**Comment by helpermethod** [comment]
I did this multiple times but the problem persists. I have a feeling there is some sort of state locally which doesn't exist on the CI.

**Comment by helpermethod** [comment]
@marc0der The problem was an additional newline 🤦 . *If* it was a newline. Anyways, it works now.

**Comment by marc0der** [comment]
Cool, I ran scalafmt and pushed the result to master :grimacing:

That seemed to have cleared up the problem.

**Comment by helpermethod** [comment]
Thanks!

**Pull request closed without merging**
