### PR TITLE
Migration for Apache Spark v3.0.2

### PR DESCRIPTION
**Pull request by Opalo**

### CODE REVIEW

**Comment by marc0der** [comment]
@Opalo Thanks for the PR. Looks like scalafmt is failing. Happy to merge after that is fixed.

**Comment by Opalo** [comment]
Sure, will do it till the end of the week. I was editing on GH directly so it makes sense :)

**Comment by Opalo** [comment]
@marc0der it looks like that all the checks have passed.

**Review by marc0der — APPROVED** [review]

**Comment by marc0der** [comment]
Thanks for contributing!

**Pull request merged**
