### PR TITLE
Add Java 13ea13

### PR DESCRIPTION
**Pull request by eddumelendez**

### CODE REVIEW

**Comment by marc0der** [comment]
Looks like your PR broke the build. Did you run this locally?

**Comment by marc0der** [comment]
Please ensure that your code compiles and that the URLs are correct. I've fixed it for now and pushed my changes to master to get the build green again.

**Comment by eddumelendez** [comment]
Sorry for that @marc0der. I noticed what was wrong late. I will be more careful next time.

**Comment by marc0der** [comment]
No probs, it's fixed and ea13 has been released. Thanks for contributing.

**Pull request merged**
